title: blickfangQ2
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6364141351077706
  brandStrength: 0.3811393277719617
  rhythmicContrast: 0.5
  brandColors:
    - '#000000'
    - '#f6f5ef'
    - '#c7c3b7'
    - '#625a50'
    - '#a7a194'
  lightness: 0.479373173089698
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: blickfangQ2
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.57885
layout_spectrum: 1
