name: blickfangQ2
favicon: null
layout_spectrum: 0.7588843945413828
typography_spectrum: 0.06164423003792763
title: blickfangQ2
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3811393277719617
  lightness: 0.47937317308969796
  saturation: 0.6364141351077706
  rhythmicContrast: 0.31889396836049855
purpose: []
